api/urls.py
from django.urls import path,re_path
from . import views
from  django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

urlpatterns = [
    path('admin-login/',views.AdminLoginAPIView.as_view(),name='api-admin-login'),
    path('home-api/',views.HomeAPIView.as_view(),name='api-home'),
    path('all-testimonials/',views.TestimonialAPIView.as_view(),name='api-all-testimonials'),
    path('property-list/',views.PropertyListAPIView.as_view(),name='api-property-list'),
    path('property-detail/<int:property_id>/',views.PropertyDetailAPIView.as_view(),name='api-property-detail'),
    path('contact-us-data/',views.ContactUspageListAPIView.as_view(),name='api-contact-us-data'),
    path('contact-create/', views.CreateContactUspageAPIView.as_view(), name='api-contact-create'),
    path('contact-delete/<int:contact_id>/', views.DeleteContactUspageAPIView.as_view(), name='api-contact-delete'),
    path('property-create/', views.CreatePropertyAPIView.as_view(), name='api-property-create'),
    path('property-update/<int:property_id>/', views.UpdatePropertyAPIView.as_view(), name='api-property-update'),
    path('property-delete/<int:property_id>/', views.DeletePropertyAPIView.as_view(), name='api-property-delete'),
    path('dist-property-create/', views.CreateDistPropertyAPIView.as_view(), name='dist-property-create'),
    path('dist-property-update/<int:property_id>/', views.UpdateDistPropertyAPIView.as_view(), name='dist-property-update'),
    path('dist-property-delete/<int:property_id>/', views.DeleteDistPropertyAPIView.as_view(), name='dist-property-delete'),


    path('create-blog/', views.CreateBlogAPIView.as_view(), name='api-create-blog'),
    path('blog-update/<int:blog_id>/', views.UpdateBlogAPIView.as_view(), name='api-blog-update'),
    path('blog-delete/<int:blog_id>/', views.DeleteBlogAPIView.as_view(), name='api-blog-delete'),


    path('create-state/', views.CreateStateAPIView.as_view(), name='api-create-state'),

    path('create-district/', views.CreateDistrictAPIView.as_view(), name='api-create-district'),

    path('create-locality/', views.CreateLocalityAPIView.as_view(), name='api-create-locality'),

    path('create-testimonial/', views.CreateTestimonialAPIView.as_view(), name='api-create-testimonial'),
    path('delete-testimonial/<int:testimonial_id>/', views.DeleteTestimonialAPIView.as_view(), name='api-delete-testimonial'),



    path('create-gallery-image/', views.CreateGalleryImageAPIView.as_view(), name='api-create-gallery-image'),
    path('delete-gallery-image/<int:image_id>/', views.DeleteGalleryImageAPIView.as_view(), name='api-delete-gallery-image'),


    path('property-filter/', views.PropertySearchAPIView.as_view(), name='api-property-filter'),



]

realrupees_app/urls.py
from django.urls import path,re_path
from . import views
from  django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

urlpatterns = [
    path('',views.home,name='home'),
    path('contact_us',views.contact_us,name='contact_us'),
    path('about_us',views.about_us,name='about_us'),
    path('test',views.test,name='test'),
    path('property',views.property,name='property'),
    path('property/<int:property_id>/', views.details_property, name='details_property'),
    path('blog_page',views.blog_page,name='blog_page'),
    path('blog_detail',views.blog_detail,name='blog_detail'),
    path('admin',views.admin,name='admin'),
    path('admin_login',views.admin_login,name='admin_login'),
    path('login',views.login,name='login'),
    path('contact',views.contact,name='contact'),
    path('contact_page',views.contact_page,name='contact_page'),
    path('delete_contacts/<int:opening_id>/',views.delete_contacts,name='delete_contacts'),
    path('add_property',views.add_property,name='add_property'),
    path('delete_property/<int:opening_id>/',views.delete_property,name='delete_property'),
    path('edit_property/<int:content_id>/',views.edit_property,name='edit_property'),
    path('add_dist_property',views.add_dist_property,name='add_dist_property'),
    path('delete_dist_property/<int:opening_id>/',views.delete_dist_property,name='delete_dist_property'),
    path('edit_disT_property/<int:content_id>/',views.edit_dist_property,name='edit_dist_property'),
    path('blog_content',views.blog_content,name='blog_content'),
    path('add_blog',views.add_blog,name='add_blog'),
    path('blog_detail/<int:blog_id>/',views.blog_detail,name='blog_detail'),
    path('blog',views.blog,name='blog'),
    path('edit_blog/<int:blog_id>/',views.edit_blog,name='edit_blog'),
    path('delete_dist_blogs/<int:opening_id>/',views.delete_dist_blogs,name='delete_dist_blogs'),
    path('add_state',views.add_state,name='add_state'),
    path('add_district',views.add_district,name='add_district'),
    path('add_locality',views.add_locality,name='add_locality'),
    path('district_page/<int:district_id>/', views.district_page, name='district_page'),
    path('property/search/', views.property_search, name='property_search'),
    path('property_id_search',views.property_id_search,name='property_id_search'),
    path('add_testimonials',views.add_testimonials,name='add_testimonials'),
    path('delete_testimonials/<int:opening_id>/',views.delete_testimonials,name='delete_testimonials'),
    path('add_images',views.add_images,name='add_images'),
    path('delete_gallery_image/<int:opening_id>',views.delete_gallery_image,name='delete_gallery_image'),
    path('edit_gallery_image/<int:opening_id>/', views.edit_gallery_image, name='edit_gallery_image'),
    path('logout',views.logout,name='logout'),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


realrupees_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Contact_Uspage(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone_no = models.CharField(max_length=255)
    message = models.TextField()


class State_name(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class District_name(models.Model):
    state = models.ForeignKey(State_name, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Locality(models.Model):
    state = models.ForeignKey(State_name, on_delete=models.CASCADE)
    district = models.ForeignKey(District_name, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name



class Add_Property(models.Model):
    STATUS_CHOICES = (
        ('For Sale', 'For Sale'),
        ('Sold', 'Sold'),
    )
    
    heading = models.CharField(max_length=100)
    subheading = models.TextField()
    property_id = models.CharField(max_length=255)
    
    state = models.ForeignKey(State_name, on_delete=models.CASCADE, default=1)  # Provide default value
    district = models.ForeignKey(District_name, on_delete=models.CASCADE, default=1)  # Provide default value
    locality = models.ForeignKey(Locality, on_delete=models.CASCADE, default=1)
    paragraph = models.TextField(default='none')
    youtube_url = models.URLField(max_length=200, null=True, blank=True)
    google_map_link = models.URLField(max_length=200, null=True, blank=True)
    images = models.ManyToManyField('PropertyImage', related_name='properties')
    price = models.CharField(max_length=255, default='None')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='For Sale')
    type  = models.CharField(max_length=255,default='None')
    
    def __str__(self):
        return self.heading

class PropertyImage(models.Model):
    image = models.ImageField(upload_to='mamamia_images/')
    
    def __str__(self):
        return self.image.name


class Add_Dist_Property(models.Model):
    image = models.ImageField(upload_to='mamamia_images/')
    heading = models.CharField(max_length=100)
    subheading = models.TextField()
    property_id = models.CharField(max_length=255)
    button_text = models.CharField(max_length=255, blank=True, default='Default Button Text')
    button_url = models.URLField(blank=True, default='https://example.com')
    def __str__(self):
        return self.heading


class Blog_Content(models.Model):
    image = models.ImageField(upload_to='mamamia_images/')
    heading = models.CharField(max_length=100)
    paragraph = models.TextField()
    date = models.DateField(max_length=255)
    
    def __str__(self):
        return self.heading


class Testimonial(models.Model):
    name = models.CharField(max_length=255)
    
    
    review = models.TextField()

    def __str__(self):
        return self.name


# Create your models here.



class GalleryImage(models.Model):

    TYPE_CHOICES = (
        ('image', 'Image'),
        ('video', 'Video'),
    )

    image = models.ImageField(
        upload_to='swiper_images/',
        blank=True,
        null=True
    )

    video = models.FileField(
        upload_to='swiper_videos/',
        blank=True,
        null=True
    )

    type = models.CharField(
        max_length=10,
        choices=TYPE_CHOICES,
        default='image'
    )

    title = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )

    description = models.TextField(
        blank=True,
        null=True
    )

    def __str__(self):
        return self.title or "Gallery Item"



realrupees_app/templates/add_awiper_img.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Swiper Image</title>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
      rel="stylesheet"
    />
  </head>
  <style>
    @import 'https://fonts.googleapis.com/css?family=Montserrat|Open+Sans';

    .navbar-brand {
      font-family: 'Montserrat', sans-serif;
      text-transform: uppercase;
    }

    .navbar .nav {
      font-family: 'Open Sans', sans-serif;
      text-transform: uppercase;
      letter-spacing: 3px;
      font-size: 1.5rem;
      padding: 10px;
    }

    .navbar-inverse {
      background-color: #057405;
    }

    .navbar-inverse .navbar-nav > li > a:hover,
    .navbar-inverse .navbar-nav > li > a:focus {
      background-color: #044e04;
    }

    .dropdown-menu {
      background-color: #006b00;
    }

    .dropdown-menu > li > a:hover,
    .dropdown-menu > li > a:focus {
      background-color: #002200;
    }

    .navbar-inverse .navbar-brand,
    .navbar-inverse .navbar-nav > li > a {
      color: #ffffff;
    }

    .navbar-inverse .navbar-brand:hover,
    .navbar-inverse .navbar-nav > li > a:hover {
      color: #ffcc00;
    }
  </style>
  <body>
    <header
      class="navbar navbar-inverse navbar-fixed-top bs-docs-nav"
      role="banner"
    >
      <div class="container">
        <div class="navbar-header">
          <button
            class="navbar-toggle"
            type="button"
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1"
          >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="./" class="navbar-brand">Real Rupees</a>
        </div>
        <nav
          class="collapse navbar-collapse bs-navbar-collapse"
          id="bs-example-navbar-collapse-1"
          role="navigation"
        >
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'property' %}">Property</a></li>
            <li><a href="{% url 'about_us' %}">About Us</a></li>
            <li><a href="{% url 'contact_us' %}">Contact Us</a></li>
            <li><a href="{% url 'test' %}">Testimonials</a></li>
            <li class="nav-item">
              <a class="nav-link" href="tel:+1234567890"
                ><i class="fas fa-phone-alt"></i>9747858495</a
              >
            </li>
          </ul>
        </nav>
      </div>
    </header>

    <br /><br /><br /><br /><br />

    <div class="container" style="margin-top: 40px">
      <div class="heading">
        <h1 class="text-center">Add Images / Videos</h1>
      </div>
    </div>

    <!-- Add Form -->
    <div class="container" style="margin-top: 40px">
      <form
        method="post"
        action="{% url 'add_images' %}"
        enctype="multipart/form-data"
      >
        {% csrf_token %}

        <label for="title">Title:</label>
        <input
          type="text"
          class="form-control"
          name="title"
          placeholder="Enter title"
        />
        <br />

        <label for="description">Description:</label>
        <textarea
          class="form-control"
          name="description"
          rows="4"
          placeholder="Enter description"
        ></textarea>
        <br />

        <label for="type">Type:</label>
        <select name="type" class="form-control">
          <option value="image">Image</option>
          <option value="video">Video</option>
        </select>
        <br />

        <label for="image">Image:</label>
        <input type="file" class="form-control" name="image" accept="image/*" />
        <br />

        <label for="video">Video:</label>
        <input type="file" class="form-control" name="video" accept="video/*" />
        <br />

        <input
          type="submit"
          class="btn"
          value="Submit"
          style="color: #fff; background-color: #bd4419"
        />
      </form>
    </div>

    <!-- Display Table -->
    <div class="container" style="margin-top: 40px">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Type</th>
            <th>Image</th>
            <th>Video</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
          {% for c in add_images %}
          <tr>
            <td>{{ c.id }}</td>
            <td>{{ c.title }}</td>
            <td>{{ c.description }}</td>
            <td>{{ c.type }}</td>

            <td>
              {% if c.image %}
              <img
                src="{{ c.image.url }}"
                alt="thumb"
                style="width: 100px; height: 100px"
              />
              {% else %}
              <span>No image</span>
              {% endif %}
            </td>

            <td>
              {% if c.video %}
              <a href="{{ c.video.url }}" target="_blank">View Video</a>
              {% else %}
              <span>No video</span>
              {% endif %}
            </td>

            <td>
              <a
                href="{% url 'edit_gallery_image' c.id %}"
                class="btn btn-primary"
                >Edit</a
              >
              <a
                href="{% url 'delete_gallery_image' c.id %}"
                class="btn btn-danger"
                >Delete</a
              >
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="mt-5 text-center">
        <a style="color: #bd4419" href="">Go Back</a>
      </div>
    </div>

    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
  </body>
</html>

realrupees_app/templates/add_property.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}"> -->

    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">
    
    <title>About Us </title>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet" />
</head>

    <style>
        @import 'https://fonts.googleapis.com/css?family=Montserrat|Open+Sans';

        .navbar-brand {
            font-family: 'Montserrat', sans-serif;
            text-transform: uppercase
        }

        .navbar .nav {
            font-family: 'Open Sans', sans-serif;
            text-transform: uppercase;
            letter-spacing: 3px;
            font-size: 1.5rem;
            padding: 10px;
        }

        .navbar-inverse {
            background-color: #057405
        }

        .navbar-inverse .navbar-nav>.active>a:hover,
        .navbar-inverse .navbar-nav>li>a:hover,
        .navbar-inverse .navbar-nav>li>a:focus {
            background-color: #044e04
        }

        .navbar-inverse .navbar-nav>.active>a,
        .navbar-inverse .navbar-nav>.open>a,
        .navbar-inverse .navbar-nav>.open>a,
        .navbar-inverse .navbar-nav>.open>a:hover,
        .navbar-inverse .navbar-nav>.open>a,
        .navbar-inverse .navbar-nav>.open>a:hover,
        .navbar-inverse .navbar-nav>.open>a:focus {
            background-color: #003300
        }

        .dropdown-menu {
            background-color: #006B00
        }

        .dropdown-menu>li>a:hover,
        .dropdown-menu>li>a:focus {
            background-color: #002200
        }

        .navbar-inverse {
            background-image: none;
        }

        .dropdown-menu>li>a:hover,
        .dropdown-menu>li>a:focus {
            background-image: none;
        }

        .navbar-inverse {
            border-color: #003300
        }

        .navbar-inverse .navbar-brand {
            color: #FFFFFF
        }

        .navbar-inverse .navbar-brand:hover {
            color: #FFCC00
        }

        .navbar-inverse .navbar-nav>li>a {
            color: #FFFFFF
        }

        .navbar-inverse .navbar-nav>li>a:hover,
        .navbar-inverse .navbar-nav>li>a:focus {
            color: #FFCC00
        }

        .navbar-inverse .navbar-nav>.active>a,
        .navbar-inverse .navbar-nav>.open>a,
        .navbar-inverse .navbar-nav>.open>a:hover,
        .navbar-inverse .navbar-nav>.open>a:focus {
            color: #FFCC00
        }

        .navbar-inverse .navbar-nav>.active>a:hover,
        .navbar-inverse .navbar-nav>.active>a:focus {
            color: #FFCC00
        }

        .dropdown-menu>li>a {
            color: #FFFFFF
        }

        .dropdown-menu>li>a:hover,
        .dropdown-menu>li>a:focus {
            color: #FFCC00
        }

        .navbar-inverse .navbar-nav>.dropdown>a .caret {
            border-top-color: #FFFFFF
        }

        .navbar-inverse .navbar-nav>.dropdown>a:hover .caret {
            border-top-color: #FFFFFF
        }

        .navbar-inverse .navbar-nav>.dropdown>a .caret {
            border-bottom-color: #FFFFFF
        }

        .navbar-inverse .navbar-nav>.dropdown>a:hover .caret {
            border-bottom-color: #FFFFFF
        }

        .whatsapp-icon {
    position: fixed;
    bottom: 20px; /* Adjust as needed */
    right: 20px; /* Adjust as needed */
    z-index: 9999; /* Ensure it appears above other content */
}
</style>
<body>
    <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="./" class="navbar-brand">Real Rupees</a>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" id="bs-example-navbar-collapse-1" role="navigation">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'property' %}">Property</a>
                    </li>
                    <li>
                        <a href="{% url 'about_us' %}">About Us</a>
                    </li>
                    <li>
                        <a href="{% url 'contact_us' %}">Contact Us</a>
                    </li>
                    <li>
                        <a href="{% url 'test' %}">Testimonals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="tel:+1234567890"><i class="fas fa-phone-alt"></i>9747858495</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <br><br><br><br><br>

    <div class="container" style="margin-top: 40px;">
        <h1 style="text-align: center;">Property Page</h1>
        <form method="post" action="{% url 'add_property' %}" enctype="multipart/form-data">
            {% csrf_token %}
            
            <!-- Inputs for Images -->
            <label for="images">Images:</label>
            <input type="file" class="form-control" name="images" accept="image/*" multiple required>
            <br>
            
            <!-- Inputs for Property Details -->
            <label for="heading">Heading:</label>
            <input type="text" class="form-control" name="heading" required>
            <br>
            <label for="subheading">Subheading:</label>
            <input type="text" class="form-control" name="subheading" required>
            <br>
            <label for="property_id">Property Id:</label>
            <input type="text" class="form-control" name="property_id" required>
            <br>
            <label for="paragraph">Paragraph:</label>
            <textarea class="form-control" id="editor" name="paragraph" required></textarea>
            <br>
            <label for="youtube_url">YouTube URL:</label>
            <input type="url" class="form-control" name="youtube_url">
            <br>
            <label for="google_map_link">Google Map Link:</label>
            <input type="url" class="form-control" name="google_map_link">
            <br>
 
            <label for="google_map_link">Price:</label>
            <input type="text" class="form-control" name="price">
            <br>
            <label for="status">Status:</label>
            <select class="form-control" name="status">
                <option value="For Sale">For Sale</option>
                <option value="Sold">Sold</option>
            </select>
            <br>
            <label for="google_map_link">Type:</label>
            <input type="text" class="form-control" name="type">
            <br>
            <!-- State Dropdown -->
<!-- State Dropdown -->
<label for="state">State:</label>
<select name="state_id" id="id_state" class="form-control">
    <option value="Select The State">Select The State</option>
    {% for state in states %}
        <option value="{{ state.id }}">{{ state.name }}</option>
    {% endfor %}
</select>
<br>

<!-- District Dropdown -->
<label for="district">District:</label>
<select name="district_id" id="id_district" class="form-control">
    <option value="Select The District">Select The District</option>
    {% for district in districts %}
        <option value="{{ district.id }}" data-state="{{ district.state.id }}">{{ district.name }}</option>
    {% endfor %}
</select>
<br>

<!-- Locality Dropdown -->
<label for="locality">Locality:</label>
<select name="locality_id" id="id_locality" class="form-control">
    <option value="Select The Locality">Select The Locality</option>
    {% for locality in localities %}
        <option value="{{ locality.id }}" data-district="{{ locality.district.id }}">{{ locality.name }}</option>
    {% endfor %}
</select>
<br>

            
            

        
            <!-- Submit Button -->
            <input type="submit" class="btn" value="Submit" style="color:#fff; background-color: #bd4419;">
        </form>
        
    </div>
    <h2 class="text-center">Added Properties</h2>
<table class="table" style="margin-top: 30px;">
    <thead>
        <tr>
            <th>Images</th>
            <th>Heading</th>
            <th>Subheading</th>
            <th>Property Id</th>
            <th>Paragraph</th>
            <th>Price</th>
            <th>Status</th>
            <th>Type</th>
            <th>State</th>
            <th>District</th>
            <th>Locality</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for property in add_property %}
        <tr>
            <td>
                {% for img in property.images.all %}
                <img src="{{ img.image.url }}" alt="thumb" style="width: 50px; height: 50px;">
                {% empty %}
                <span>No image</span>
                {% endfor %}
            </td>
            <td>{{ property.heading }}</td>
            <td>{{ property.subheading }}</td>
            <td>{{ property.property_id }}</td>
            <td>{{ property.paragraph|safe }}</td>
            <td>{{ property.price }}</td>
            <td>{{ property.status }}</td>
            <td>{{ property.type }}</td>
            <td>{{ property.state.name }}</td>
            <td>{{ property.district.name }}</td>
            <td>{{ property.locality.name }}</td>
            <td>
                <a href="{% url 'edit_property' property.id %}" class="btn btn-sm" style="background-color: #000B41; color: #fff;">Edit</a>
                <a href="{% url 'delete_property' property.id %}" class="btn btn-sm" style="background-color: #fb0404; color: #ffffff; margin-top: 10px;">Delete</a>
                 
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
    
 
    
    





    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <script>
  
  CKEDITOR.replace('editor');

  
document.addEventListener('DOMContentLoaded', function() {
    const stateDropdown = document.getElementById('id_state');
    const districtDropdown = document.getElementById('id_district');
    const localityDropdown = document.getElementById('id_locality');
    
    function filterOptions(dropdown, key, value) {
        for (let option of dropdown.options) {
            if (option.getAttribute(key) === value || value === '') {
                option.style.display = '';
            } else {
                option.style.display = 'none';
            }
        }
    }

    stateDropdown.addEventListener('change', function() {
        const selectedState = this.value;
        filterOptions(districtDropdown, 'data-state', selectedState);
        filterOptions(localityDropdown, 'data-district', '');
    });
    
    districtDropdown.addEventListener('change', function() {
        const selectedDistrict = this.value;
        filterOptions(localityDropdown, 'data-district', selectedDistrict);
    });
    
    // Initialize district and locality options based on the initial selected state
    const initialSelectedState = stateDropdown.value;
    filterOptions(districtDropdown, 'data-state', initialSelectedState);
    filterOptions(localityDropdown, 'data-district', '');
});














    
    document.getElementById("whatsapp-button").addEventListener("click", function () {
          var phoneNumber = "+91 9747858495";
          var message = "Hello, I'd like to get in touch with you!";
          var url = "https://api.whatsapp.com/send?phone=" + phoneNumber + "&text=" + encodeURIComponent(message);
          window.open(url, "_blank");
      });







    
    
      document.getElementById('editor').addEventListener('keydown', function(e) {
        if (e.key === 'Enter' && !e.shiftKey) {
            // Prevent the default behavior (line break) and insert a newline character
            e.preventDefault();
            const textarea = document.getElementById('editor');
            const cursorPos = textarea.selectionStart;
            const textBefore = textarea.value.substring(0, cursorPos);
            const textAfter = textarea.value.substring(cursorPos);

            textarea.value = textBefore + '\n' + textAfter;

            // Move the cursor to the next line
            textarea.setSelectionRange(cursorPos + 1, cursorPos + 1);
        }
    });
    
  </script>
  </body>
  </html>